spring:
  application:
    name: Status Monitor
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/website
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
